ENH: Enable stain normalization for multiple images
microsoft/hi-ml pull request #587
Opened 2022-08-31 08:48 UTC by harshita-s

Enable stain normalization to work with multiple images (e.g., when a bag of tiles is given as input).

2022-08-31 08:52 UTC, vale-salvatelli commented on hi-ml/src/health_ml/utils/data_augmentations.py
> +            return self.stain_normalize(img, self.reference_mean, self.reference_std)
Can we extend the tests to cover this case?

2022-08-31 08:53 UTC, vale-salvatelli requested changes
Can we extend the tests to cover this case?

2022-08-31 09:30 UTC, harshita-s commented
Extended the test to cover the case
> Can we extend the tests to cover this case?

2022-09-01 08:17 UTC, vale-salvatelli approved these changes

2022-09-01 12:52 UTC, merged